### ISSUE TITLE
Übergabe von Parametern an puppeteer.launch ermöglichen

### ISSUE THREAD

**Issue by BernhardLinz** [foxriver76/ioBroker.puppeteer#10]
Wenn ich die `main.ts` richtig interpretiere wird dort puppeteer in Zeile 21 per
`this.browser = await puppeteer.launch({ headless: true, defaultViewport: null });`
aufgerufen.

Es wäre nun hilfreich wenn man Parameter zu Chrome-Engine übergeben könnte um ggf. das Rendern weiter zu beinflussen:
`this.browser = await puppeteer.launch({ headless: true, defaultViewport: null, args: ['--disable-lcd-text', '--disable-composited-antialiasing'] });`

Aktueller Anlass ist die Verwendung der Screenshots für ePaper-Displays. Die Screenshots weisen bei JPG trotz einer Qualität von 100% ein Anti-Aliasing auf was insbesondere bei der Verwendung von Rot zu Artefakten auf den Displays führt (schwarzen Pixel um rote Flächen herum.
Beitrag im Forum: https://forum.iobroker.net/post/1070535

Soweit ich das verstanden habe könnte man alle mögliche Chromium-Parameter ( https://peter.sh/experiments/chromium-command-line-switches/ ) so übergeben

**Comment by foxriver76** [comment]
Sollte mit 0.3.0 nun möglich sein in der Adapter Config zusätzliche Argumente zu hinterlegen, welche dem Puppeteer Prozess mitgegeben werden.
