### ISSUE TITLE
Option für "--force-device-scale-factor=" hinzufügen

### ISSUE THREAD

**Issue by BernhardLinz** [foxriver76/ioBroker.puppeteer#16]
Bei Screenshots ist gerade Text / Buchstaben "verwaschen" / hat einen "blur".
Eine Lösung bei Puppeteer dagegen ist den Scale-Faktor zu erhöhen. Dazu muss man Chrome mit der Option

`--force-device-scale-factor=4`

aufrufen - die 4 steht für 4-fache Auflösung. Dementsprechend würde ein 200x100 Pixel großer Screenshot dann 800x400 groß, dafür in in guter Qualität und ohne Blur

Es wäre schön wenn das Konfigurierbar wäre, ggf. eine Option das man allgemein Parameter an den Chrome-Browser durchreichen könnte beim SendTo Befehl.

---------------------------------------
in screenshots, text/letters are “washed out”/have a “blur”.
A solution for Puppeteer, however, is to increase the scale factor. To do this you have to use Chrome with the option

`--force-device-scale-factor=4`

- the 4 stands for 4 times the resolution. Accordingly, a 200x100 pixel screenshot would then be 800x400, but in good quality and without blur

It would be nice if this were configurable, perhaps an option so that you could pass general parameters to the Chrome browser with the SendTo command.

**Comment by foxriver76** [comment]
Can you try if it works to send the following with the message e.g. 

```
      viewportOptions: {
        width: 800,
        height: 600,
        deviceScaleFactor: 4,
      },
```

You should be able to send everything specified [here](https://pptr.dev/api/puppeteer.viewport) in the `viewportOptions`, hence `width` and `height`  are mandatory rest is optional.

**Comment by BernhardLinz** [comment]
Yes, it works! A hint in the documentation would be usefull ;-)
