### ISSUE TITLE
warning nach installation 0.3.0

### ISSUE THREAD

**Issue by arteck** [foxriver76/ioBroker.puppeteer#20]
<html>
<body>

puppeteer has an invalid jsonConfig: [{"instancePath":"/items/additionalArgs/items/0","schemaPath":"#/items/allOf/19/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"filter"},"message":"must NOT have additional properties"},{"instancePath":"/items/additionalArgs","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/25/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match \"else\" schema"}]
--

</body>
</html>

**Comment by foxriver76** [comment]
I think schema has an issue also see https://github.com/ioBroker/adapter-react-v5/issues/387
