### ISSUE TITLE
Adapter kann nicht installiert werden, Process exited with code 25

### ISSUE THREAD

**Issue by xyzorange2** [foxriver76/ioBroker.puppeteer#4]
$ iobroker add puppeteer --host raspberrypi
NPM version: 8.11.0
Installing iobroker.puppeteer@0.2.6... (System call)
host.raspberrypi Cannot install iobroker.puppeteer@0.2.6: 1
ERROR: Process exited with code 25

Gibt es noch Abhängigkeiten, welche ich vorher installieren muss? Habe das direkt in ioBroker über "Adapter" zu installieren versucht...

**Comment by foxriver76** [comment]
Wenn alles korrekt eingerichtet ist, versucht der Adapter alle Abhängigkeiten mit zu installieren. Gerne mal `sudo apt update` auf der Kommandozeile ausführen und dann nochmal installieren. Ansonsten mal bitte `iob add puppeteer --debug`

**Comment by xyzorange2** [comment]
Laut debug muss ich chromium und chromium-browser installieren, weil ich auf arm64 unterwegs bin und das chromium binary dafür nicht verfügbar ist. Das werde ich heute Abend nach Dienstschluss ausprobieren, vielen Dank!

iob add puppeteer --debug
NPM version: 8.15.0
Installing iobroker.puppeteer@0.2.6... (System call)
npm ERR! code 1
npm ERR! path /opt/iobroker/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh /tmp/install-919e2c7d.sh
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with:
npm ERR!
npm ERR!  sudo apt install chromium
npm ERR!
npm ERR!
npm ERR!  sudo apt install chromium-browser
npm ERR!
npm ERR! /opt/iobroker/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119
npm ERR!                     throw new Error();

**Comment by xyzorange2** [comment]
*** UPDATE: ***

Funktioniert jetzt alles. Vielen Dank!
